In [8]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import pandas as pd


# 데이터 불러오기
data = pd.read_csv('C:\Projects\data_test1.csv')

# [데이터 확인] 상위 5행 불러오기
data.head()

C:\Users\kygam\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3,4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

   cloud  min_cloud_hei  rain temp visiblity  wind_dire  wind_spd  class
0      7             35     0  7.6      1000         20         4      0
1      6             35     0  6.8      1000         19         5      0
2      3             35     0  5.6      1000         18         6      0
3      3             35     0  5.6      1000         18         6      0
4      3             35     0  5.6      1000         18         6      0

In [9]:
# [데이터 확인] 데이터 정보
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143244 entries, 0 to 143243
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   cloud          143244 non-null  int64
 1   min_cloud_hei  143244 non-null  int64
 2   rain           143244 non-null  int64
 3   temp           143244 non-null  object
 4   visiblity      143244 non-null  object
 5   wind_dire      143244 non-null  int64
 6   wind_spd       143244 non-null  int64
 7   class          143244 non-null  int64
dtypes: int64(6), object(2)
memory usage: 8.7+ MB

In [10]:
# 컬럼 타입 변경 : 문자형 -> 숫자형 
# error 옵션 : 숫자로 변경할 수 없는 데이터면 NaN 처리
# NaN 처리된 데이터는 0으로 바뀜
data = data.apply(pd.to_numeric, errors = 'coerce').fillna(0)

# 바뀐 데이터 타입 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143244 entries, 0 to 143243
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   cloud          143244 non-null  int64
 1   min_cloud_hei  143244 non-null  int64
 2   rain           143244 non-null  int64
 3   temp           143244 non-null  float64
 4   visiblity      143244 non-null  float64
 5   wind_dire      143244 non-null  int64
 6   wind_spd       143244 non-null  int64
 7   class          143244 non-null  int64
dtypes: float64(2), int64(6)
memory usage: 8.7 MB

In [11]:
# [데이터 확인] 데이터 요약, 관련 통계
data.describe()

,cloud,min_cloud_hei,rain,temp,visiblity,wind_dire,wind_spd,class
count,143244.000000,143244.000000,143244.000000,143244.000000,143244.000000,143244.000000,143244.000000,143244.000000
mean,5.429219,47.870396,0.711625,16.997084,857.024378,20.615467,10.928290,0.486582
std,2.653740,63.284277,3.731022,8.930215,257.020878,11.320337,7.753975,0.499822
min,0.000000,0.000000,0.000000,-2.900000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,10.000000,0.000000,10.800000,800.000000,9.000000,5.000000,0.000000
50%,7.000000,25.000000,0.000000,18.400000,1000.000000,23.000000,8.000000,0.000000
75%,8.000000,40.000000,0.000000,24.400000,1000.000000,31.000000,15.000000,1.000000
max,8.000000,240.000000,57.000000,35.800000,1000.000000,36.000000,43.000000,1.000000

In [12]:
# pandas 데이터 프레임 객체 -> numpy 배열 객체
# 학습 데이터 
train_data = data[['cloud','min_cloud_hei','rain', 'temp', 'visiblity','wind_dire','wind_spd']].to_numpy()
# 타겟 데이터 
target=data['class'].to_numpy()

# train_test_split : 학습 / 테스트 데이터 셋 분리 모듈
# 테스트 셋 사이즈 = 30%
train_input, test_input, train_target, test_target = train_test_split(
train_data, target, test_size = 0.3)

# 데이터 셋 분리 확인
print(train_input.shape, test_input.shape)

(100270, 7) (42974, 7)

In [13]:
# 스케일링 
ss = StandardScaler()

# train 데이터 조정
ss.fit(train_input)

# train / test 데이터 스케일 조정, 표준 점수로 변환
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [14]:
# 가우시안 나이브베이즈 객체 생성
nb = GaussianNB()

# 학습
nb_fitted = nb.fit(train_scaled, train_target)
y_pred = nb_fitted.predict(train_scaled)

# 정확도 확인
print(f"[Gaussian Naive Bayes] Accuracy : {nb.score(train_scaled, train_target)}")
print(f"[Gaussian Naive Bayes] Accuracy : {nb.score(test_scaled, test_target)}")
print("----------------------------------------------------------------")

# 테스트 
print(nb_fitted.predict_proba(train_scaled)[[1, 7, 12]])
print("----------------------------------------------------------------")
print(f"[Test #1] 예측값 : {nb_fitted.predict(train_scaled)[1]}")
print(f"[Test #2] 예측값 : {nb_fitted.predict(train_scaled)[7]}")
print(f"[Test #3] 예측값 : {nb_fitted.predict(train_scaled)[12]}")
print("----------------------------------------------------------------")
print(f"[Test #1] 실제값 : {train_target[1]}")
print(f"[Test #2] 실제값 : {train_target[7]}")
print(f"[Test #3] 실제값 : {train_target[12]}")


# 추가 테스트 (결항)
test = [[8 ,15, 4, 20.5, 600, 3, 18]]
pred = nb_fitted.predict(test)
y_true = 1

print("----------------------------------------------------------------")
print(f"예측값 : {pred} ")
print(f"실제값 : {y_true}")

# 혼동 행렬 : 성능 확인
confusion_matrix(train_target, y_pred)

[Gaussian Naive Bayes] Accuracy : 0.7090954423057744
[Gaussian Naive Bayes] Accuracy : 0.7108949597431005
----------------------------------------------------------------
[[1.03194322e-50 1.00000000e+00]
 [3.08957507e-02 9.69104249e-01]
 [7.17385946e-06 9.99992826e-01]]
----------------------------------------------------------------
[Test #1] 예측값 : 1
[Test #2] 예측값 : 1
[Test #3] 예측값 : 1
----------------------------------------------------------------
[Test #1] 실제값 : 1
[Test #2] 실제값 : 0
[Test #3] 실제값 : 1
----------------------------------------------------------------
예측값 : [1]
실제값 : 1

array([[47235,  4315],
       [24854, 23866]], dtype=int64)